
package br.com.hypersales.framework.dao.protheus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HYPERSALESSOAP", targetNamespace = "http://fw.rozac.com.br:81/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HYPERSALESSOAP {


    /**
     * Consulta Generica
     * 
     * @param query
     * @return
     *     returns br.com.hypersales.framework.dao.protheus.STRUCTRETURN
     */
    @WebMethod(operationName = "GETSQL", action = "http://fw.rozac.com.br:81/GETSQL")
    @WebResult(name = "GETSQLRESULT", targetNamespace = "http://fw.rozac.com.br:81/")
    @RequestWrapper(localName = "GETSQL", targetNamespace = "http://fw.rozac.com.br:81/", className = "br.com.hypersales.framework.dao.protheus.GETSQL")
    @ResponseWrapper(localName = "GETSQLRESPONSE", targetNamespace = "http://fw.rozac.com.br:81/", className = "br.com.hypersales.framework.dao.protheus.GETSQLRESPONSE")
    public STRUCTRETURN getsql(
        @WebParam(name = "QUERY", targetNamespace = "http://fw.rozac.com.br:81/")
        String query);

    /**
     * Gera novo pedido de Vendas
     * 
     * @param structsetsalesorder
     * @return
     *     returns br.com.hypersales.framework.dao.protheus.STRUCTRETURN
     */
    @WebMethod(operationName = "INSERT", action = "http://fw.rozac.com.br:81/INSERT")
    @WebResult(name = "INSERTRESULT", targetNamespace = "http://fw.rozac.com.br:81/")
    @RequestWrapper(localName = "INSERT", targetNamespace = "http://fw.rozac.com.br:81/", className = "br.com.hypersales.framework.dao.protheus.INSERT")
    @ResponseWrapper(localName = "INSERTRESPONSE", targetNamespace = "http://fw.rozac.com.br:81/", className = "br.com.hypersales.framework.dao.protheus.INSERTRESPONSE")
    public STRUCTRETURN insert(
        @WebParam(name = "STRUCTSETSALESORDER", targetNamespace = "http://fw.rozac.com.br:81/")
        SETSALESORDERSTRUCT structsetsalesorder);

    /**
     * Insert Token
     * 
     * @param structtoken
     * @return
     *     returns br.com.hypersales.framework.dao.protheus.STRUCTRETURN
     */
    @WebMethod(operationName = "INSERTTOKENS", action = "http://fw.rozac.com.br:81/INSERTTOKENS")
    @WebResult(name = "INSERTTOKENSRESULT", targetNamespace = "http://fw.rozac.com.br:81/")
    @RequestWrapper(localName = "INSERTTOKENS", targetNamespace = "http://fw.rozac.com.br:81/", className = "br.com.hypersales.framework.dao.protheus.INSERTTOKENS")
    @ResponseWrapper(localName = "INSERTTOKENSRESPONSE", targetNamespace = "http://fw.rozac.com.br:81/", className = "br.com.hypersales.framework.dao.protheus.INSERTTOKENSRESPONSE")
    public STRUCTRETURN inserttokens(
        @WebParam(name = "STRUCTTOKEN", targetNamespace = "http://fw.rozac.com.br:81/")
        TOKENSTRUCT structtoken);

    /**
     * Validação de usuarios	 
     * 
     * @param userid
     * @param password
     * @return
     *     returns br.com.hypersales.framework.dao.protheus.STRUCTRETURN
     */
    @WebMethod(operationName = "ISUSERVALID", action = "http://fw.rozac.com.br:81/ISUSERVALID")
    @WebResult(name = "ISUSERVALIDRESULT", targetNamespace = "http://fw.rozac.com.br:81/")
    @RequestWrapper(localName = "ISUSERVALID", targetNamespace = "http://fw.rozac.com.br:81/", className = "br.com.hypersales.framework.dao.protheus.ISUSERVALID")
    @ResponseWrapper(localName = "ISUSERVALIDRESPONSE", targetNamespace = "http://fw.rozac.com.br:81/", className = "br.com.hypersales.framework.dao.protheus.ISUSERVALIDRESPONSE")
    public STRUCTRETURN isuservalid(
        @WebParam(name = "USERID", targetNamespace = "http://fw.rozac.com.br:81/")
        String userid,
        @WebParam(name = "PASSWORD", targetNamespace = "http://fw.rozac.com.br:81/")
        String password);

}
